platform :ios, '8.0'
use_frameworks!

target 'Realm-JSONAPI_Example' do
  pod 'Realm-JSONAPI', :path => '../'

  target 'Realm-JSONAPI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
