use_frameworks!

target 'RLMObject-JSONAPI_Example' do
  pod 'RLMObject-JSONAPI', :path => '../'

  target 'RLMObject-JSONAPI_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
